### ISSUE TITLE
error sed

### ISSUE THREAD

**Issue by Pedisx** [c4rrilat0r/sedgf#1]
When I do it, and show me this 
run -----> echo "https://example.com?redirect=https://evil.com&param1=test1&param2=test2" | qsreplace newval | sedgf -replace newval redirect

AND 
show me this:
sed: -e expression #1, char 77: unknown option to `s'

**Comment by c4rrilat0r** [comment]
Hi! I don't see that is happens to me. I changed some things so if you wanna update and test it again I would be nice! Thank you a lot for you feedback!
